# configuration for signet

# suffixes for files in the GWAS directory
# each phenotype has a prefix, for example HR for heart rate
# then files in the DATA/GWAS directory would be
# HR_GWAS_rows.txt HR_rsid_GRCh38p13.txt HR_
gwas_filename: _GWAS_rows.txt
snploc_filename: _rsid_GRCh38p13.txt
feature_initscore_filename: feature_initscore_one.txt


# Required common directory and files
# The recommended directory structure is that the toplevel directory has subdirectories for
#   signet source code repo
#   DATA (including GWAS data)
#   RESULTS
# data_dir and results_dir are relative to toplevel
toplevel: ../
data_dir: DATA
results_dir: RESULTS
# these are subdirectories of DATA
ppi_filename: PROTEIN/human_annotated_PPIs.txt
trrust_filename: TRRUST/trrust.human.txt
gene_filename: ENSEMBL/ensembl_gene.txt

# shouldn't need this anymore
protein_gene_filename: PROTEIN/uniprot_gene.tab


#Optional project-specific files: include as *_genes.txt
#For example, QRS_coloc_genes.txt, cosmic_genes.txt



#-----------------------------------------------------------------------------------#
#Extracting SNP locations from Ensembl:
#first extract gwasrows given pubid - save as "phenotype_GWAScat.txt", in data dir
#then, extract the rsid lists:
#utils_data.GWAScat_rows(phenotype_list, GWAS_dir, project_datadir)
#output saved as "phenotype + _GWAScat_rsid.txt" in data/GWAS_catalogue
#next, upload this list/file to ensembl to download location file
#Make sure to use GRCh38.p13 version and under Filters {Variant source: sbSNP, Variant name: choose file}
#name downloaded location file as "phenotype_GWAScat_rsid_GRCh38p13.txt", MAKE sure tsv! save in data dir
